# Generated by Django 6.0.3 on 2026-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomGiftOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("frame", "Photo Frame"),
                            ("mug", "Photo Mug"),
                            ("album", "Photo Album"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reference_image", models.ImageField(upload_to="custom-orders/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready"),
                            ("delivered", "Delivered"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="gift",
            name="category",
            field=models.CharField(
                choices=[
                    ("frames", "Frames"),
                    ("albums", "Albums"),
                    ("mugs", "Mugs"),
                    ("desk", "Desk Gifts"),
                    ("prints", "Prints"),
                ],
                default="frames",
                max_length=20,
            ),
        ),
    ]
