# Generated by Django 6.0.3 on 2026-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_access_owner_portal",
            field=models.BooleanField(default=False),
        ),
    ]
